[tool.black]
line-length = 79

[tool.isort]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "SECOND_PARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_third_party = ["PyQt5", "pytest"]
known_second_party = ["bubblesub"]
known_first_party = ["quality_check"]
multi_line_output = 3
include_trailing_comma = true
